### ISSUE TITLE
한승진 멘토님과 식사 자리 가지기

### ISSUE THREAD

**Issue by javelinsman** [CHIroong/V2A#1]
* 실전문제연구단에 회의비 결제 관련 문의
* 한승진 멘토님께 메일로 문의
* (확인이 늦어지실 경우) 한승진 멘토님께 전화로 문의

**Comment by jyoonsong** [comment]
안녕하세요 한승진 멘토님,
저는 예전 실로암복지관에 인터뷰 차 방문했던 서울대학교 HCI랩 최길웅 님과 함께 연구를 진행하고 있는 송재윤이라고 합니다. 시험 등 여러 가지에 쫓기다가 학기가 끝나고 방학이 되어서야 다시 프로젝트를 본격적으로 재개해서, 연락이 늦어진 점 정말 사과드립니다.

연구에 대한 논의가 어느 정도 진행이 되어서 골격을 잡은 상황인데, 팀장님께 한 번 검토받고 여러 가지 조언을 여쭙고 싶습니다. 길웅님을 통해 인터뷰 내용이나 웹접근성에 대해 알려주신 것들을 전해 들으며, 팀장님께서 저희 프로젝트 멘토가 되어주신 것은 정말 행운이라고 생각했습니다. 그래서 멘토님과 함께 셋이서 여러 이야기를 나눌 식사 자리를 마련하고 싶은데, 시간이 괜찮으신지 여쭙고자 메일을 드립니다. 

시간은 **17일(화) 혹은 18일(수) 혹은 19일(목) 저녁** 중 편하신 시간이면 좋을 것 같고,
장소는 X-Corps 프로그램에서 지원금을 제공한다고 하여, **봉천역 빕스 혹은 정담은보쌈**를 생각 중에 있습니다. 혹시 편하신 다른 선택지가 있으시면 말씀해주십시오.

다시 한 번 흔쾌히 저희 멘토가 되어주셔서 정말 감사드립니다.
바쁘시겠지만 시간이 되신다면 꼭 뵐 수 있었으면 좋겠습니다.
좋은 하루 되십시오 :)

---

**굵은 글씨** = 미확정 사항 (제 주관적 의견이 다분히 반영되었으니 수정해주세요 ㅎㅎ)

**Comment by javelinsman** [comment]
굵은 글씨 전부 좋아요!

팀장님께서 한 번 검토해주시시고 여러 가지 조언을 여쭙고 싶습니다.
->
팀장님께 한 번 검토받고 여러 가지 조언을 여쭙고 싶습니다.

이것만 수정 부탁드릴게요!

**Comment by jyoonsong** [comment]
### 한승진 멘토님 메일을 받고난 뒤 수정본

안녕하세요 한승진 멘토님,
저는 예전 실로암복지관에 인터뷰 차 방문했던 서울대학교 HCI랩 최길웅 님과 함께 연구를 진행하고 있는 송재윤이라고 합니다. 시험 등 여러 가지에 쫓기다가 학기가 끝나고 방학이 되어서야 다시 프로젝트를 본격적으로 재개해서, 연락이 늦어진 점 정말 사과드립니다.

제안해주신 대로 모바일 앱 기획 제안서에 '서울대학교 컴퓨터공학부' 혹은 '서울대학교 인간-컴퓨터 상호작용 연구실'와의 연계를 명시하시면, 저희가 전반적인 자문에 참여하도록 하겠습니다. 다만 산학협력단은 저희와 관련이 없는 기관이며, 연계에 대한 공식적인 인증 절차가 필요할 경우에는 교수님께 허락을 구해야 할 것 같습니다. 그렇지만 않다면 전혀 문제될 것이 없고, 오히려 도움이 되어드릴 수 있어 굉장히 기쁩니다.

또 저희가 진행하던 프로젝트가 어느 정도 진행이 되어서 골격을 잡은 상황인데, 팀장님께 한 번 검토받고 여러 가지 조언을 여쭙고 싶습니다. 길웅님을 통해 인터뷰 내용이나 웹접근성에 대해 알려주신 것들을 전해 들으며, 팀장님께서 저희 프로젝트 멘토가 되어주신 것은 정말 행운이라고 생각했습니다. 그래서 멘토님과 함께 셋이서 여러 이야기를 나눌 식사 자리를 마련하고 싶은데, 시간이 괜찮으신지 여쭙고자 메일을 드립니다. 

시간은 **17일(화) 혹은 18일(수) 혹은 19일(목) 저녁** 중 편하신 시간이면 좋을 것 같고,
장소는 X-Corps 프로그램에서 지원금을 제공한다고 하여, **봉천역 빕스 혹은 정담은보쌈**을 생각 중에 있습니다. 혹시 편하신 다른 선택지가 있으시면 말씀해주십시오.

다시 한 번 흔쾌히 저희 멘토가 되어주셔서 정말 감사드립니다.
바쁘시겠지만 시간이 되신다면 꼭 뵐 수 있었으면 좋겠습니다.
좋은 하루 되십시오 :)

**Comment by jyoonsong** [comment]
### 교수님께 나눔과 꿈 사업 협력 기관으로 등록 허락 맡기

교수님 안녕하세요.
최길웅입니다.

접근성 관련 연구를 진행하면서 인터뷰와 실험 참여자 모집, 그리고 연구 전반적인 부분에서 검토를 받는 등 실**로암 시각장애인 복지관으로부터 굉장히 많은 도움을 받았는데, 이번에는 반대로 도움을 드릴 기회**가 생겨 이렇게 메일을 드리게 되었습니다.
다름이 아니라 이번에 **실로암 시각장애인 복지관에서 '나눔과 꿈'이라는 공모전에 참여**한다고 합니다.
이때 지원서에서 **협력기관으로 '서울대학교 인간-컴퓨터 상호작용 연구실'을 언급**하고, 실제로 저와 인턴을 하고 계신 재윤님으로부터 전반적인 자문을 받았으면 하는 상황입니다.
아래는 한승진 팀장님께서 보내온 사업 소개 전문입니다.

나눔과꿈 사업은 삼성에서 후원하고 사회복지공동모금회에서 진행하는 지원사업입니다.
저희는 이 사업에 시각장애인이 의약품명을 바코드, QR코드,﻿ 음성입력, 키보드입력 등 다양한 방식으로
입력하면 공공데이터를 수집하여 접근성에 맞도록 출력해주는 모바일 앱 개발을 진행할 계획입니다.
그 과정에서 아무래도 소프트웨어적인 부분은 외부 자문이 필요할 것이라 생각이 듭니다.
그리고 현재 연계 기관은 시각장애인 유관기관 외 시각장애인 당사자를 포함하여 서울대학교 귀 연구실과 함께
기술자문을 받으면서 진행해도 좋을 것 같습니다.
추후 본 사업이 진행될 때에는 다른 시각장애인 ﻿관련 기관과 귀 연구실과도 만날 수 있는 계기를 통해
추후 협력 범위도 넓힐 수 있는 효과도 있으리라 생각됩니다.

저와 재윤님의 경우, **실로암 복지관으로부터 많은 도움을 받아 왔고, 사업 내용이 흥미롭기에 자문에 적극적으로 참여할 의지가 있는 상태**입니다.
하지만 협력 기관 명에 연구실 이름을 명시해야 하는 만큼, 교수님께 허락을 구하고자 메일을 드립니다.
나눔과꿈 공모전에 대한 자세한 내용은 [이 링크](https://www.sharinganddream.org:9004/main/apply/apply.php)에 나와있습니다.

답변해주시면 정말 감사드리겠습니다.
좋은 하루 되십시오


---

뭔가 연구실 인턴보다는 정식 소속원인 사람이 요구하는 게 훨씬 정당한 것 같아서 길웅님 인칭으로 썼습니다. 원하시면 바꿔도 좋아요 ㅎㅎ
