### ISSUE TITLE
full page screenshot 관련 이슈

### ISSUE THREAD

**Issue by jyoonsong** [CHIroong/V2A#10]
### 라이브러리
* [full-page-screen-capture-chrome-extension](https://github.com/mrcoles/full-page-screen-capture-chrome-extension)

### 문제
1. 클라이언트 사이드에서 캡처를 하므로 **scroll되는 과정이 눈에 보임.** 처음 스크롤 위치를 기억했다가 엄청 빨리 끝내고 다시 원위치시켜놓는 방식 외에 더 좋은 방법 없을지.
=> 잠정적 해결책: 일단 더 좋은 방법 없는 것 같다.

2. **iframe permission**
This permission is required in order to scroll the inner contents of iframes or framesets.
=> 잠정적 해결책: 처음에 한 번 받으면 된다.

3. permission을 받아도 **iframe/framesets 스크롤에 문제가 있다.** 예컨대 mysnu는 framesets로 되어 있다는데 스크롤이 안되고 찍힌다. 
=> 잠정적 해결책: 마이스누 같은 올드한 홈페이지는 제외한다.

**Comment by javelinsman** [comment]
2, 3번 같은 경우에 그냥 mysnu.ac.kr에 들어가서 javascript로 스크롤을 하려고 하면 그 사이트 내부 구현이 iframe으로 되어 있기 때문에 스크롤이 안 된다는 거죠? 말씀하신 것처럼 일단 연구단계에서는 제외해도 될 것 같아요.
