### ISSUE TITLE
Web page segmentation 외부 라이브러리 찾아보기

### ISSUE THREAD

**Issue by javelinsman** [CHIroong/V2A#3]
1. webzeitgeist 1저자인 http://ranjithakumar.net/ 에 가봤지만 소득 없음
    * webzeitgeist의 경우 학회 전후로 demo page가 열려 있었다고 함. 지금은 닫힌 듯.

1. 관련된 논문들은 아래와 같이 좀 있지만 material 공개 안 되어 있어서 직접 구현해야 함 
    * http://www.cs.cmu.edu/~lbing/pub/sigir2014-bing.pdf
    * https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7415394

1. 이거를 깔아봤지만 텍스트 몇개 추출해주고 말아서, 코드를 자세히 보진 않았으나 별로 같음 
   * https://github.com/nik0spapp/sdalg 

1. http://bom.ciens.ucv.ve/ 여길 가 봤지만 약간 믿을만하지 못함. 그래도 제공하는 걸 다 살펴 봤는데
    * chrome extension 설치는 안 됨
    * [java 라이브러리](http://pagelyzer.openpreservation.org/)는 뭔가 "training" 항목도 있고 해서 우리가 당장 활용 가능한게 아닐 것 같음
        * 그래도 ground-truth 같은 말은 우리가 원하는 거랑 적합한듯
    * js 라이브러리는 뭐 어떻게 활용하라는 건지 모르겠음. 메인 함수에 달린 주석 5줄이 다라서...

**Comment by jyoonsong** [comment]
1. 씹힐 각오 하고 연락을 해보는 건 어떻게 생각하세요? 확률은 낮지만 혹시라도 관심을 보여서 contribution을 해줄 경우 저자에도 추가될 수 있는 혜택이 있지 않을까 싶은데

2. 링크가 안 보이네요 ㅠㅠ

3. 일단은 html 태그 기반인 것으로 보이는데, 나중에 저희도 스크린샷 베이스의 visual segmentation의 한계를 메꾸기 위해 사용해도 좋을 것 같아요. 내용이 잘린 것 같아서 여기까지만 ㅋㅋ

4. 들어가자마자 오...! 했슴다. 저희가 하려는 것과 매우 유사(거의 동일)한 것 같은데요? pagelyzer가 (1) 스크린샷 찍고 (2) web segmentation 알고리즘 쓰고 (3) uses MarcAlizer to return the result. 라고 되어있는데 거의 다 갖춘 것 아닌가요?
자세한 코드는 아직 못봤는데 어찌 됐든 위대한 발견인 것 같아요. 보다보니 Web Segmentation 자체만 주제로 하는 연구도 넘쳐나는 같아서 여기에 조금만 contribution을 덧붙여서 가져와도 괜찮을 것 같다는 생각이 들었어요. 코드는 시험 끝나고 바로 확인해볼게요!

**Comment by javelinsman** [comment]
1. 메일 보내는 거 괜찮은 것 같아요, 이슈 하나 새로 올릴게요!
2. 링크 수정했습니다!
3. ㅋㅋㅋㅋ 4번 내용이었는데 3번에 붙어있었어요
4. 네 아무래도 pagelyzer 위주로 파봐야할 것 같아요. 살펴보고 다시 코멘트 올릴게요.

**Comment by javelinsman** [comment]
https://github.com/openpreserve/pagelyzer
에 적힌 instruction대로 수행했는데 여러 오류가 발생해서 결국은 test 실패.
(mvn compile 명령이 최상단 폴더에서는 SUCCESS하는데 그 이후의 작업에서 mainClasss argument가 specify 되지 않았다는 둥 오류 발생)

http://scape.lip6.fr/scape-demo-sites/pagelyzer/#scoremessage
여기서 demo를 시험해볼 수 있는데, 예시 URL 입력해보니 동작 안함.

**Comment by javelinsman** [comment]
차라리 pagelyzer 소스코드를 다 읽고 분석한다음 새로 짜거나 이식하는 게 더 나을 것 같다는 생각이 드는 중. 다음에 할 일은 js 라이브러리 읽어보고 가능하면 테스트 해보기.

**Comment by javelinsman** [comment]
http://www1.se.cuhk.edu.hk/~textmine/code/segmentation/
읽어본 논문 하나에서 공개한 소스. 근데 논문이 어려워서(혹은 설명이 불친절해서) 이해하기는 쉽지 않다.

웹 세그멘테이션 전체 코드는 아니고 논문에서 설명하는 알고리즘의 일부분에 대한 것

**Comment by javelinsman** [comment]
장랩 다니는 성호의 추천

관련 키워드

* Image segmentation: https://arxiv.org/abs/1711.10370
* Bounding box classification
* Semantic segmentation

기타 조언

* 일단 너가 하고싶은거 하려면 데이터부터 만들어야함. 페이지 몇 천 개 정도.
* amazon mechanical turk 알아보라. 수십만원 주면  할수 있다. 대신 너가 툴을 만들어야하는데 그건 할수있겠지
* 딥러닝으로 하지 말고 대충 전처리 후 if else하는 걸 추천
* [PyTorch semantic segmentation 튜토리얼](https://github.com/GunhoChoi/Kind-PyTorch-Tutorial/tree/master/12_Semantic_Segmentation) 추천

**Comment by javelinsman** [comment]
외부 라이브러리를 찾기보다 Webzeitgeist 저자가 보내주는 설명 혹은 Purely Vision-based를 읽고 직접 구현하는 게 나을 것 같고, 세그멘테이션 자체는 현재 가장 중요한 게 아니라는 재민이형의 조언을 따라 이 이슈는 마무리.
