### ISSUE TITLE
웹 페이지의 headless rendering

### ISSUE THREAD

**Issue by javelinsman** [CHIroong/V2A#5]
client-side에서 계산하지 않고 server-side에서 계산해야 될 경우를 대비해 알아본 결과

* 일반적으로 웹 브라우저에서 접속하는 형태가 아니라 화면 없이(?) 렌더링하는 걸 "Headless"라는 키워드로 부르는 듯
* [PhantomJS](http://phantomjs.org/)라는 것이 있었으나 이젠 [suspended](https://github.com/ariya/phantomjs/issues/15344)되었고
* [Chrome headless](https://developers.google.com/web/updates/2017/04/headless-chrome)가 있다고 함
* 김젼의 추천: https://github.com/GoogleChrome/puppeteer

**Comment by jyoonsong** [comment]
오 phantomJS 엄청 많이 들어봤어요. screen capture가 마치 저희를 기다렸다는 듯이 있군요
개발은 멈췄지만, 멈춘 시점이 고작 몇 달 전인 것을 보아 outdated 할 염려는 없는 듯요! 굿!

**Comment by javelinsman** [comment]
URL이 같아도 context에 따라 화면이 달라질 수 있으므로 server-side에서 headless browser로 렌더링해서 계산하기 곤란함. HTML, CSS, JS등 리소스를 전부 보낸 다음 거기서 합쳐서 렌더링해야 하는데 tedious한 작업이 될 것으로 예상. Headless rendering은 잠정적으로 고려하지 않기로 결정.
